language: julia
os:               # Travis CI has support for Linux and macOS
  - linux
  - osx
julia:            # Julia versions to run tests on
  - 1.0
  - 1.1
  - nightly

after_success:  # only run this if test pass
  - julia -e 'using Pkg; Pkg.add("Coverage");
      using Coverage; Codecov.submit(Codecov.process_folder())';