name = "MyPackage2"
uuid = "e1660eca-ac97-11e9-13f5-dfbcb2e6b7e1"
authors = ["Fredrik Ekre <ekrefredrik@gmail.com>"]
version = "0.1.0"

[deps]
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]